### PR TITLE
fix: Bugs & changed code style

### LINKED ISSUE #5: FS-1: Implement IO system

### LINKED ISSUE #6: FS-2: Refactor classes following Java code convention

### PR DESCRIPTION
**Pull request by aoyako**
Fix bugs in bitmap (serialize and deserialize).
Change code style (uppercase to lowercase in method names)
Added some error classes

### CODE REVIEW

File: second-semester/Filesystem/src/main/java/ua/knu/Main.java [hunk 1]
```diff
@@ -3,9 +3,77 @@
...
 import ua.knu.elements.Bitmap;
+import ua.knu.elements.Manipulator.ByteManipulator;
+import ua.knu.filesystem.FileManager;
+import ua.knu.io.disk.Disk;
 
 public class Main {
-    public static void main(String[] args) {
-        DiskInitializer.Initialize();
+    public static void main(String[] args) throws Exception {
+        Disk disk = DiskInitializer.Initialize();
```
Comment (Vlad-Yakimenko) [inline second-semester/Filesystem/src/main/java/ua/knu/Main.java]: Why does this method name start with a capital letter?

File: second-semester/Filesystem/src/main/java/ua/knu/elements/Descriptor.java [hunk 2]
```diff
@@ -3,6 +3,7 @@
 import ua.knu.elements.Manipulator.ByteManipulator;
 import ua.knu.elements.Manipulator.Manipulator;
 
+//Descriptor represents file descroptor
 public class Descriptor extends FSElement {
```
Comment (Vlad-Yakimenko) [inline second-semester/Filesystem/src/main/java/ua/knu/elements/Descriptor.java:11]: Could you use Lombok instead of declaring getters and setters explicitly?

File: second-semester/Filesystem/src/main/java/ua/knu/elements/Descriptor.java [hunk 3]
```diff
@@ -14,38 +15,41 @@ public Descriptor() {
...
+    
+    public FSElement deserialize(byte[] data, int pos) {
+        length = manipulator.readInt(data, pos);
+        if (length > (((long) 1) << 15)) {
+            length = -1;
+        }
         
         for (int i = 0; i < 3; i++) {
-            blocks[i] = manipulator.ReadInt(data, pos + 4 * i);
+            blocks[i] = manipulator.readInt(data, pos + 4 * (i + 1));
```
Comment (Vlad-Yakimenko) [inline second-semester/Filesystem/src/main/java/ua/knu/elements/Descriptor.java]: Please declare variables with more sensefull names than "i"

File: second-semester/Filesystem/src/main/java/ua/knu/elements/DirectoryEntry.java [hunk 4]
```diff
@@ -0,0 +1,46 @@
+package ua.knu.elements;
+
+import ua.knu.elements.Manipulator.ByteManipulator;
+import ua.knu.elements.Manipulator.Manipulator;
+
+// DirectoryEntry represents directory entry
+public class DirectoryEntry extends FSElement {
```
Comment (Vlad-Yakimenko) [inline second-semester/Filesystem/src/main/java/ua/knu/elements/DirectoryEntry.java:11]: Lombok

File: second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java [hunk 5]
```diff
@@ -0,0 +1,189 @@
...
+                if (entry.getName() == 0) {
+                    return absolutePos;
+                }
+
+                absolutePos++;
+                currentPosition += entry.size();
+            }
+        }
+
+        throw new DirectoryFullException("Directory is full");
```
Comment (Vlad-Yakimenko) [inline second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java:59]: Please add clarity which one directory is full

File: second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java [hunk 6]
```diff
@@ -0,0 +1,189 @@
...
+                // Found one
+                if (desc.getLength() < 0) {
+                    return absolutePos;
+                }
+                currentPosition += desc.size();
+                absolutePos++;
+            }
+        }
+
+        throw new DirectoryFullException("Directory is full");
```
Comment (Vlad-Yakimenko) [inline second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java:83]: Same as above

File: second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java [hunk 7]
```diff
@@ -0,0 +1,189 @@
...
+
+            // Load next block
+            byte[] data = oft.loadBlock(0, i);
+            if (data == null) {
+                return;
+            }
+
+            // Iterate over block to find entry with filename
+            int currentPosition = 0;
+            while (currentPosition + entry.size() <= oft.getDisk().Blocksize()) {
```
Comment (Vlad-Yakimenko) [inline second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java]: Looks like disk methods start with capital letters

File: second-semester/Filesystem/src/main/java/ua/knu/filesystem/oft/OpenFileTable.java [hunk 8]
```diff
@@ -0,0 +1,203 @@
+package ua.knu.filesystem.oft;
+
+import ua.knu.elements.Descriptor;
+import ua.knu.elements.DirectoryEntry;
+import ua.knu.io.disk.Disk;
+
+import java.util.List;
+import java.util.ArrayList;
+
+class OFTEntry {
```
Comment (Vlad-Yakimenko) [inline second-semester/Filesystem/src/main/java/ua/knu/filesystem/oft/OpenFileTable.java]: Lombok is fit for POJO classes like this one

File: second-semester/Filesystem/src/main/java/ua/knu/filesystem/oft/OpenFileTable.java [hunk 9]
```diff
@@ -0,0 +1,203 @@
...
+    
+    public void setBlock(byte[] b) {
+        block = b;
+    }
+}
+
+// OpenFileTable (OFT) represents a tableof open files
+// @note Directory must always be open
+// @note You should modify this class, and/or its interface
+public class OpenFileTable implements OFTInterface {
```
Comment (Vlad-Yakimenko) [inline second-semester/Filesystem/src/main/java/ua/knu/filesystem/oft/OpenFileTable.java:13]: What about split two classes into two java files or make OFTEntry nested class

File: second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java (hunk 5 above)
Comment (aoyako) [reply second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java:59]: We have only 1 directory 🙃

File: second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java (hunk 6 above)
Comment (aoyako) [reply second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java:83]: Same as above

File: second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java (hunk 5 above)
Comment (Vlad-Yakimenko) [reply second-semester/Filesystem/src/main/java/ua/knu/filesystem/FileManager.java:59]: 😅

**Comment by Vlad-Yakimenko** [comment]
LGTM!
